"""CALENDAR-SYMMETRIC SURROGATES.

Masking gap-spanning increments took the over-firing from 9.39x to 0.84x, but 15 of
45 tests still failed uniformity. The residue is an asymmetry in construction: the
data is a smooth solar process sampled on an IRREGULAR CALENDAR, while surrogates
were phase-randomised on the COMPRESSED INDEX AXIS, where the calendar has already
been flattened away.

Fix: build surrogates the way the data is built -- phase-randomise on the FULL daily
grid, then subsample through the same 1,064-break mask. Data and surrogate then
share a calendar as well as a spectrum.

The synthetic dataset is likewise kept on the full grid, so its own surrogates are
generated by exactly the same operation. No padding, no resampling back and forth.
"""
import numpy as np, os, sys, time
from scipy.stats import kstest, norm
from multiprocessing import Pool
import sys as _s, os as _o
_s.path.insert(0, _o.path.join(_o.path.dirname(_o.path.abspath(__file__)), "..", "search"))
import wl_sweep as W

FULL=np.arange(len(W.OV)); SUB=np.where(W.OV)[0]; NF=len(FULL)
def fill(ch):
    v=W.M[W.ix[ch]].astype(float); m=np.isfinite(v)
    return np.interp(FULL,FULL[m],v[m])
XF=np.vstack([norm.ppf((np.argsort(np.argsort(fill(c)))+0.5)/NF) for c in W.WL])

def screen(YF,rng):
    """common phase screen on the full grid -> full grid"""
    F=np.fft.rfft(YF,axis=1)
    ph=rng.uniform(0,2*np.pi,F.shape[1]); ph[0]=0.0
    if NF%2==0: ph[-1]=0.0
    return np.fft.irfft(F*np.exp(1j*ph)[None,:],n=NF,axis=1)

def all_stats(Z):
    return np.array([W.stat(W.FORMS[fn](*[Z[i] for i in q])) for q,fn in W.TESTS])

NSUR=int(os.environ.get("NSUR","300"))
def trial(seed):
    rng=np.random.default_rng(seed)
    YF=screen(XF,rng)                       # synthetic data, full grid, no 4-way
    obs=all_stats(YF[:,SUB])                # observed = subsampled through real mask
    S=np.array([all_stats(screen(YF,rng)[:,SUB]) for _ in range(NSUR)])
    return np.array([(1.0+(S[:,t]>=obs[t]).sum())/(1.0+NSUR) for t in range(len(W.TESTS))])

if __name__=="__main__":
    NT=int(sys.argv[1]) if len(sys.argv)>1 else 200
    print("calendar-symmetric surrogates: %d trials x %d sur x %d tests"%(NT,NSUR,len(W.TESTS)))
    t0=time.time()
    with Pool(80) as p: P=np.array(p.map(trial,range(3100,3100+NT),chunksize=1))
    print("%.1f s"%(time.time()-t0))
    bad=[]
    for t in range(len(W.TESTS)):
        ps=P[:,t][np.isfinite(P[:,t])]
        if kstest(ps,"uniform").pvalue<0.05/len(W.TESTS): bad.append(t)
    allp=P[np.isfinite(P)]
    print("  POOLED mean p %.4f (expect 0.5)  frac<0.05 %.4f (expect 0.05)  ratio %.2fx"
          %(allp.mean(),(allp<0.05).mean(),(allp<0.05).mean()/0.05))
    print("  tests failing uniformity at Bonferroni: %d of %d"%(len(bad),len(W.TESTS)))
    for t in bad[:8]:
        q,fn=W.TESTS[t]; print("     %-44s %s"%(" / ".join(W.WL[i] for i in q),fn))
